# Uncomment the next line to define a global platform for your project


target 'VHYunSDKDemo_LSS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#  use_frameworks!
  platform :ios, '9.0'
  
  pod 'VHCore',:path => '../../vhallyun_sdk_base/VHCore.podspec'
  pod 'VHYun_LSS',:path=>'../VHYun_LSS.podspec'
  

  pod 'Masonry'
  pod 'SDWebImage'
end

#target 'ScreenLive' do
#  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#  use_frameworks!
#
#  platform :ios, '12.0'
#
#  pod 'VHYun_ScreenShare',:path=>'../../vhallyun_sdk_vrtc/VHYun_ScreenShare.podspec'
#end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'YES'

      if config.name == 'Release'
          config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
      else
          config.build_settings['BITCODE_GENERATION_MODE'] = 'marker'
      end

      cflags = config.build_settings['OTHER_CFLAGS'] || ['$(inherited)']

      if config.name == 'Release'
          cflags << '-fembed-bitcode'
      else
          cflags << '-fembed-bitcode-marker'
      end

      config.build_settings['OTHER_CFLAGS'] = cflags
    end
  end
end
